### ISSUE TITLE
How to invite

### ISSUE THREAD

**Issue by sp1r1tak** [fffffffffffffffffff19/Senor-Hilter-Bot#2]
This may very well be aa stupid question, but how do I invite the bot to my server? I got it running but I can't figure out how to invite it. Thanks

**Comment by fffffffffffffffffff19** [comment]
No, is not a stupid question, i added a guide on how to do this in the current bot readme, you need to go to your application in the developer portal and create directly from it, according to the image that I will leave here. ![image](https://i.imgur.com/4pETVDv.png)
